"use client";
import Image from "next/image";
import { useEffect, useState } from "react";
import { Heart, Image as ImageIcon, MessageCircle, Send } from "lucide-react";
import dnjGameLogo from "@/assets/brand/DNJGAME_01.png";
import type { AnimDir } from "@/features/app/types";
import type { GalleryPage, Moment } from "@/types/experience";

const images = ["/mock/moments/dnj-feed-01.png", "/mock/moments/dnj-feed-02.png"];
const motion = (dir: AnimDir) => ({ animation: dir === "left" ? "slideInLeft 280ms cubic-bezier(.22,1,.36,1) both" : "fadeUp 220ms cubic-bezier(.22,1,.36,1) both" });
const status = (moment: Moment) => moment.publicationStatus === "private" ? "Privado" : moment.moderationStatus === "pending" ? "Em moderação" : "Publicado";

function Card({ moment, index }: { moment: Moment; index: number }) {
  const [liked, setLiked] = useState(false); const [comment, setComment] = useState("");
  return <article className="overflow-hidden rounded-2xl" style={{ background: "var(--card)", boxShadow: "var(--shadow-card)" }}><header className="flex items-center gap-3 px-4 py-3"><span className="grid h-9 w-9 place-items-center rounded-full text-xs font-black" style={{ background: "var(--primary-alpha-15)", color: "var(--primary)" }}>DNJ</span><span className="flex-1"><strong className="block text-sm">{index ? "Rafael e amigos" : "Ana Clara"}</strong><small style={{ color: "var(--muted-foreground)" }}>Juventude DNJ</small></span></header><div className="relative"><Image src={images[index % images.length]} alt={`Momento em ${moment.placeName}`} width={1024} height={1280} className="aspect-[4/5] w-full object-cover" /><Image src={dnjGameLogo} alt="Marca d'água DNJ" width={136} height={40} className="absolute bottom-3 right-3 h-8 w-auto drop-shadow-md" /></div><div className="p-4"><button onClick={() => setLiked((value) => !value)} aria-pressed={liked} className="flex items-center gap-2 text-sm font-bold" style={{ color: liked ? "var(--secondary)" : "var(--foreground)" }}><Heart size={20} fill={liked ? "currentColor" : "none"} />{8 + index + (liked ? 1 : 0)}</button><p className="mt-3 text-sm"><strong>{index ? "Rafael" : "Ana Clara"}</strong> registrou este momento em {moment.placeName}.</p><form className="mt-3 flex items-center gap-2" onSubmit={(event) => { event.preventDefault(); setComment(""); }}><MessageCircle size={17} style={{ color: "var(--muted-foreground)" }} /><input value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Adicionar comentário..." className="min-w-0 flex-1 bg-transparent text-sm outline-none" /><button disabled={!comment.trim()} aria-label="Enviar comentário" style={{ color: "var(--primary)" }}><Send size={18} /></button></form></div></article>;
}

export function GalleryScreen({ animDir }: { animDir: AnimDir }) {
  const [tab, setTab] = useState<"public" | "mine">("public"); const [page, setPage] = useState<GalleryPage>({ items: [], nextCursor: null }); const [loading, setLoading] = useState(true);
  useEffect(() => { let live = true; fetch(tab === "public" ? "/api/mock/v1/gallery?eventId=event_dnj_curitiba_2026" : "/api/mock/v1/gallery/mine", { headers: tab === "mine" ? { authorization: "Bearer mock" } : undefined }).then((response) => response.ok ? response.json() : Promise.reject()).then((value: GalleryPage) => live && setPage(value)).catch(() => live && setPage({ items: [], nextCursor: null })).finally(() => live && setLoading(false)); return () => { live = false; }; }, [tab]);
  const changeTab = (next: "public" | "mine") => { if (next !== tab) { setLoading(true); setTab(next); } };
  return <div className="absolute inset-0 overflow-y-auto pb-28" style={{ background: "var(--background)", paddingTop: "calc(64px + var(--safe-area-top))", ...motion(animDir) }}><header className="px-5 pb-4"><h1 className="text-2xl font-black">Galeria DNJ</h1><p className="mt-1 text-sm" style={{ color: "var(--muted-foreground)" }}>Memórias que juventude está criando.</p><div className="mt-4 flex rounded-xl p-1" style={{ background: "var(--muted)" }}>{[{ id: "public" as const, label: "Galeria DNJ" }, { id: "mine" as const, label: "Meus Momentos" }].map((item) => <button key={item.id} onClick={() => changeTab(item.id)} className="flex-1 rounded-lg py-2 text-sm font-bold" style={{ background: tab === item.id ? "var(--primary)" : "transparent", color: tab === item.id ? "white" : "var(--muted-foreground)" }}>{item.label}</button>)}</div></header><main className="px-4 py-4">{loading ? <p className="py-10 text-center text-sm">Carregando momentos...</p> : page.items.length === 0 ? <div className="py-14 text-center"><ImageIcon className="mx-auto mb-2" /><strong>Nenhum momento ainda</strong></div> : tab === "public" ? <div className="mx-auto flex max-w-sm flex-col gap-4">{page.items.map((item, index) => <Card key={item.id} moment={item} index={index} />)}</div> : <div className="grid grid-cols-2 gap-3">{page.items.map((item, index) => <article key={item.id} className="overflow-hidden rounded-2xl" style={{ background: "var(--card)", boxShadow: "var(--shadow-card)" }}><Image src={images[index % images.length]} alt={`Seu momento em ${item.placeName}`} width={640} height={800} className="aspect-square w-full object-cover" /><div className="p-3"><strong className="block truncate text-sm">{item.placeName}</strong><small style={{ color: "var(--muted-foreground)" }}>{status(item)}</small></div></article>)}</div>}</main></div>;
}
