"use client";
import { useEffect, useState } from "react";
import { CheckCircle2, Clock3, Heart, MapPin, X } from "lucide-react";
import { CONFESSION_FAQ, SPIRITUAL_FAQ } from "@/features/app/fixtures";
import type { AnimDir, QueueType } from "@/features/app/types";

type QueueStage = "select" | "confirmed" | "tracking";
const label = (type: QueueType) => type === "confession" ? "Confissão" : "Direção Espiritual";
const transition = (dir: AnimDir) => ({ animation: dir === "left" ? "slideInLeft 280ms cubic-bezier(0.22,1,0.36,1) both" : "fadeUp 220ms cubic-bezier(0.22,1,0.36,1) both" });

export function QueueScreen({ animDir }: { animDir: AnimDir }) {
  const [type, setType] = useState<QueueType>(null); const [stage, setStage] = useState<QueueStage>("select"); const [position, setPosition] = useState(12);
  useEffect(() => { if (stage !== "tracking" || position <= 1) return; const id = window.setInterval(() => setPosition((value) => Math.max(1, value - 1)), 15000); return () => window.clearInterval(id); }, [position, stage]);
  const faq = type === "confession" ? CONFESSION_FAQ : SPIRITUAL_FAQ;
  const state = position === 1 ? "Você foi chamado. Dirija-se ao espaço." : position <= 3 ? "Sua vez está próxima. Permaneça por perto." : "A fila atualiza automaticamente.";
  const enter = (next: QueueType) => { setType(next); setPosition(next === "confession" ? 12 : 8); setStage("confirmed"); };
  return <div className="absolute inset-0 overflow-y-auto px-5 pb-28" style={{ background: "var(--background)", paddingTop: "calc(70px + var(--safe-area-top))", ...transition(animDir) }}>
    {stage === "select" && <><h1 className="text-2xl font-black">Fila do Espaço Esperança</h1><p className="mt-1 text-sm" style={{ color: "var(--muted-foreground)" }}>Escolha seu atendimento.</p><div className="mt-6 space-y-4">{(["confession", "spiritual"] as const).map((item) => <section key={item} className="rounded-2xl p-5" style={{ background: "var(--card)", boxShadow: "var(--shadow-card)" }}><Heart size={24} style={{ color: item === "confession" ? "var(--primary)" : "var(--chart-2)" }} /><h2 className="mt-3 text-lg font-black">{label(item)}</h2><p className="mt-1 text-sm" style={{ color: "var(--muted-foreground)" }}>{item === "confession" ? "Sacramento da reconciliação com um sacerdote." : "Diálogo sobre sua caminhada de fé e discernimento."}</p><button className="mt-5 w-full rounded-xl py-3 font-bold text-white" style={{ background: item === "confession" ? "var(--primary)" : "var(--chart-2)" }} onClick={() => enter(item)}>Entrar na fila de {label(item)}</button></section>)}</div></>}
    {stage === "confirmed" && type && <section className="mt-16 rounded-3xl p-6 text-center" style={{ background: "var(--card)", boxShadow: "var(--shadow-card)" }}><CheckCircle2 className="mx-auto" size={48} style={{ color: "var(--game)" }} /><h1 className="mt-5 text-xl font-black">Você entrou na fila de {label(type)}!</h1><p className="mt-3 text-sm leading-relaxed" style={{ color: "var(--muted-foreground)" }}>Acompanhe sua posição e permaneça próximo ao espaço quando seu número estiver se aproximando.</p><button className="mt-6 w-full rounded-2xl py-3 font-bold text-white" style={{ background: "var(--game)" }} onClick={() => setStage("tracking")}>Acompanhar minha posição</button></section>}
    {stage === "tracking" && type && <><header><button className="float-right rounded-full p-2" onClick={() => { setType(null); setStage("select"); }} aria-label="Sair da fila"><X /></button><h1 className="text-2xl font-black">{label(type)}</h1><p className="mt-1 text-sm" style={{ color: "var(--muted-foreground)" }}><MapPin className="mr-1 inline" size={14} />Espaço Esperança</p></header><section className="mt-6 rounded-3xl p-6 text-white" style={{ background: position <= 3 ? "var(--game)" : "var(--primary)" }}><span className="text-sm text-white/80">Sua posição na fila</span><strong className="mt-2 block text-6xl">{position}º</strong><p className="mt-5 flex items-center gap-2 text-sm"><Clock3 size={17} />{state}</p></section><button className="mt-4 w-full rounded-2xl py-3 font-bold" style={{ background: "var(--red-alpha-12)", color: "var(--secondary)" }} onClick={() => { setType(null); setStage("select"); }}>Sair da fila</button><section className="mt-6"><h2 className="text-lg font-black">Preparação para {label(type)}</h2><div className="mt-3 overflow-hidden rounded-2xl" style={{ background: "var(--card)", border: "1px solid var(--border)" }}>{faq.slice(0, 4).map((item) => <details key={item.q} className="border-b p-4 last:border-0" style={{ borderColor: "var(--border)" }}><summary className="cursor-pointer text-sm font-bold">{item.q}</summary><p className="mt-3 text-sm leading-relaxed" style={{ color: "var(--muted-foreground)" }}>{item.a}</p></details>)}</div></section></>}
  </div>;
}
